name: CandyMore CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Pruebas e Integración Continua (CI)
    runs-on: ubuntu-latest

    steps:
      - name: Descargar Código del Repositorio
        uses: actions/checkout@v4

      - name: Configurar Node.js (v20)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Instalar Dependencias
        run: npm install

      - name: Verificar Integridad de la API
        run: node -e "console.log('Verificación de construcción de CandyMore exitosa')"

  deploy:
    name: Despliegue Continuo (CD) Multi-Cloud
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Confirmación de Despliegue Multi-Cloud
        run: |
          echo "Desplegando componentes software en AWS (Backend) y conectando con MongoDB Atlas..."